version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
    networks:
      - lamp-docker
  www:
    depends_on:
      - db
    image: php:8.1-apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
    networks:
      - lamp-docker
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-docker
networks:
  lamp-docker:
    driver: bridge



    # this has voulme mapping changed for copy paste into portainer to manage the stack